export default {
    appName: "VITERIDE",
    title: "Enter your\nPhone\nNumber",
    subtitle: "The Silent Concierge awaits. Sign in to\nbegin your tranquil transition.",
    mobileLabel: "MOBILE IDENTIFICATION",
    phonePlaceholder: "00000 00000",
    countryCode: "+91",
    btnSendCode: "Send Verification Code",
    alternatively: "ALTERNATIVELY",
    btnGoogle: "Continue with Google",
    footerPart1: "By continuing, you agree to our ",
    footerTerms: "Terms of Service",
    footerPart2: " and\nacknowledge you have read our ",
    footerPrivacy: "Privacy Policy",
    fullStop: ".",
    dontHaveAccount: "Don't have an account? ",
    createAccount: "Create Account",

    ///Create acount Screen.
    createAccountMainTitle: "Tell us about\nyourself",
    uploadPhotoBtn: "Upload Profile Photo",
    photoHint: "HIGH RESOLUTION PORTRAIT\nRECOMMENDED",
    firstNameLabel: "FIRST NAME",
    firstNamePlaceholder: "John Doe",
    emailLabel: "EMAIL ADDRESS",
    emailPlaceholder: "johndoe@example.com",
    phoneLabel: "PHONE NUMBER",
    passwordLabel: "PASSWORD",
    passwordPlaceholder: "********",
    confirmPasswordLabel: "CONFIRM PASSWORD",
    btnCreateAccount: "Create Account",
    privacyDisclaimer: "Your information is protected by our professional privacy standards. We only use this for background verification purposes.",
    alreadyAccount: "Already have an account? ",
    login: "Login",

    ///Profile_Screen. 
    accountTitle: "Account",
    userNamePlaceholder: "Marcus Sterling",
    userPhonePlaceholder: "+91 98765 43210",
    editProfile: "Edit Profile",
    savedAddresses: "Saved Addresses",
    paymentMethods: "Payment Methods",
    emergencyContacts: "Emergency Contacts",
    settings: "Settings",
    logout: "Logout",

    //EditScreen_Profile.
    editProfileTitle: "Edit Profile",
    fullNameLabel: "FULL NAME",
    phoneLabel: "PHONE NUMBER",
    emailLabel: "EMAIL ADDRESS",
    homeCityLabel: "HOME CITY",
    defaultName: "Alexander Sterling",
    defaultPhone: "+1 (555) 012-3456",
    defaultEmail: "alex.sterling@viteride.com",
    defaultCity: "San Francisco, CA",
    accountSecurityTitle: "Account Security",
    updatePassword: "Update Password",
    lastChanged: "Last changed 3 months ago",
    saveChanges: "Save Changes",

    //SavedAddressesScreen.
    savedAddressesHeader: "Saved Addresses",
    yourPlaces: "Your\nPlaces",
    homeTitle: "Home",
    homeAddress: "2452 Ethereal Lane, Sky\nGarden",
    workTitle: "Work",
    workAddress: "99 Monolith Tower, Suite\n400",
    addNewAddress: "Add New Address",
    recentDestinationsLabel: "RECENT DESTINATIONS",
    plazaTitle: "Central Plaza",
    plazaTime: "Visited 2 hours ago",
    cafeTitle: "The Grind Ritual",
    cafeTime: "Visited yesterday",

};