export default {
    appName: "VITERIDE",
    title: "Enter your\nPhone\nNumber",
    subtitle: "The Silent Concierge awaits. Sign in to\nbegin your tranquil transition.",
    mobileLabel: "MOBILE IDENTIFICATION",
    phonePlaceholder: "00000 00000",
    countryCode: "+91",
    btnSendCode: "Send Verification Code",
    alternatively: "ALTERNATIVELY",
    btnGoogle: "Continue with Google",
    footerPart1: "By continuing, you agree to our ",
    footerTerms: "Terms of Service",
    footerPart2: " and\nacknowledge you have read our ",
    footerPrivacy: "Privacy Policy",
    fullStop: ".",
    dontHaveAccount: "Don't have an account? ",
    createAccount: "Create Account",

    ///Create acount Screen.
    createAccountMainTitle: "Tell us about\nyourself",
    uploadPhotoBtn: "Upload Profile Photo",
    photoHint: "HIGH RESOLUTION PORTRAIT\nRECOMMENDED",
    firstNameLabel: "FIRST NAME",
    firstNamePlaceholder: "John Doe",
    emailLabel: "EMAIL ADDRESS",
    emailPlaceholder: "johndoe@example.com",
    phoneLabel: "PHONE NUMBER",
    passwordLabel: "PASSWORD",
    passwordPlaceholder: "********",
    confirmPasswordLabel: "CONFIRM PASSWORD",
    btnCreateAccount: "Create Account",
    privacyDisclaimer: "Your information is protected by our professional privacy standards. We only use this for background verification purposes.",
    alreadyAccount: "Already have an account? ",
    login: "Login",

    ///Profile_Screen. 
    accountTitle: "Account",
    userNamePlaceholder: "Marcus Sterling",
    userPhonePlaceholder: "+91 98765 43210",
    editProfile: "Edit Profile",
    savedAddresses: "Saved Addresses",
    paymentMethods: "Payment Methods",
    emergencyContacts: "Emergency Contacts",
    settings: "Settings",
    logout: "Logout",

    //EditScreen_Profile.
    editProfileTitle: "Edit Profile",
    fullNameLabel: "FULL NAME",
    phoneLabel: "PHONE NUMBER",
    emailLabel: "EMAIL ADDRESS",
    homeCityLabel: "HOME CITY",
    defaultName: "Alexander Sterling",
    defaultPhone: "+1 (555) 012-3456",
    defaultEmail: "alex.sterling@viteride.com",
    defaultCity: "San Francisco, CA",
    accountSecurityTitle: "Account Security",
    updatePassword: "Update Password",
    lastChanged: "Last changed 3 months ago",
    saveChanges: "Save Changes",

    //SavedAddressesScreen.
    savedAddressesHeader: "Saved Addresses",
    yourPlaces: "Your\nPlaces",
    homeTitle: "Home",
    homeAddress: "2452 Ethereal Lane, Sky\nGarden",
    workTitle: "Work",
    workAddress: "99 Monolith Tower, Suite\n400",
    addNewAddress: "Add New Address",
    recentDestinationsLabel: "RECENT DESTINATIONS",
    plazaTitle: "Central Plaza",
    plazaTime: "Visited 2 hours ago",
    cafeTitle: "The Grind Ritual",
    cafeTime: "Visited yesterday",


    //searchScreen
    searchTitle: 'Serach',
    whereTo: 'Where to?',
    suggestions: 'Suggestions',
    savedLocations: 'Saved Locations',

    // select ride type screen
    selectRideHeader: 'Select Ride',
    vehicleTypes: 'Vehicle Types',
    optionsAvailable: 'options available',
    totalFare: 'Total Fare :',
    confirmRide: 'Confirm Ride',


    // ProposeFare screen
    placeholderForFarePrice: "Please Enter Your Fare Price",
    proposeFareHeader: 'Propose your fare',
    proposeFareHeadline1: 'Set your',
    proposeFareHeadline2: 'price.',
    recommendedRange: 'Recommended Range',
    broadcastRequest: 'Broadcast Request',
    driverOffers: 'Driver Offers',
    realTime: 'Real-time',
    counterLabel: 'Counter',
    matchedLabel: 'Matched',
    acceptBtn: 'Accept',
    declineBtn: 'Decline',
    currencySymbol: '₹',
    recommendedRangeValue: '₹320 – ₹380',



    // Finding Rides screen
    findingRideHeader: 'Finding your ride',
    findingDriverTitle: 'Finding your driver…',
    estimatedConnectionTime: 'Estimated connection time',
    paymentLabel: 'Payment',
    paymentValue: '•••• 4242',
    serviceLabel: 'Service',
    serviceValue: 'Premium XL',
    cancelRequest: 'Cancel Request',
    cancelRefundNote: 'You can cancel within the next 2 minutes for a full refund.',


    //Book For Others Screen
    bookForOthersHeader: 'Book for Others',
    bookForOthersHeadline1: 'Book for',
    bookForOthersHeadline2: 'Others',
    bookForOthersSubtitle: 'Arrange a seamless journey for your guests and track their progress in real-time.',
    bookingForSomeoneElse: 'Booking for someone else',
    bookingToggleSubtitle: 'Toggle to manage their trip',
    recipientNameLabel: 'Recipient Name',
    recipientNamePlaceholder: 'Full name',
    phoneLabel: 'Phone number',
    phonePlaceholder: '98765 43210',
    phoneCode: '+91',
    tripNoteLabel: 'Trip Note (Optional)',
    tripNotePlaceholder: 'Add a note for the driver about your guest',
    premiumServiceLabel: 'Premium Service',
    premiumServiceTitle: 'ViteRide Concierge',
    continueBtn: 'Continue',
    trackingNoteText: 'Your guest will receive a secure tracking link via SMS.',


    //In Transit screen
    inTransitHeader: 'ViteRide',
    currentFareLabel: 'Current Fare',
    currentFareValue: '₹245',
    yourJourneyLabel: 'Your Journey',
    arrivingInTitle: 'Arriving in 8 mins',
    remainingDistance: '2.4 km',
    remainingLabel: 'Remaining',
    yourDriverLabel: 'Your Driver',
    driverName: 'Alex',
    driverRatingInTransit: '4.98',
    vehicleLabel: 'Black Toyota Camry',
    vehiclePlate: '6YZA23',
    callBtn: 'Call',
    chatBtn: 'Chat',
    safetyFooterText: 'Ride protected by Onyx Safety Shield',

    //TripSummaryScreen
    tripSummaryHeader: 'Trip Summary',
    tripSummaryBrand: 'ViteRide',
    arrivalCompleteLabel: 'Arrival Complete',
    rideCompletedTitle: 'Ride Completed',
    driverNameSummary: 'Marcus Vance',
    driverVehicleSummary: 'Black Obsidian • G-552 ONYX',
    fareBreakdownLabel: 'Fare Breakdown',
    baseFareLabel: 'Base Fare',
    baseFareValue: '$12.50',
    distanceFeeLabel: 'Distance Fee (14.2 mi)',
    distanceFeeValue: '$28.40',
    timeFeeLabel: 'Time Fee (22 min)',
    timeFeeValue: '$8.80',
    totalPaidLabel: 'Total Paid',
    totalPaidValue: '$49.70',
    ratingQuestion: 'How was your journey?',
    rateDriverBtn: 'Rate Driver',
    skipFeedbackBtn: 'Skip Feedback',
    feedbackChips: ['Professional', 'Clean Car', 'Safe Driving', 'Great Conversation'],

    // Help & Support Screen
    helpSupportHeader: "Help & Support",
    helpSupportHeroTitle: "How can we\nhelp?",
    helpSupportHeroSubtitle: "Find answers to your questions or get in touch with our support team.",
    helpSupportSearchPlaceholder: "Search for help...",
    helpSupportSectionTitle: "BOOKING & RIDES",
    helpSupportStillNeedHelp: "Still need help?",
    helpSupportStillNeedHelpDesc: "Our dedicated support team is available 24/7 to assist you with any inquiries.",
    helpSupportRaiseTicket: "Raise a Ticket",
    faqQuestion1: "How do I change my pickup location?",
    faqAnswer1: "You can edit your pickup location before a driver accepts your request. Simply tap the pickup address bar on the map screen and enter the new location.",
    faqQuestion2: "What are the payment options?",
    faqAnswer2: "We accept credit/debit cards, Apple Pay, Google Pay, and ViteRide Wallet. You can manage these in the Payment section.",
    faqQuestion3: "How do I contact my driver?",
    faqAnswer3: "Once a driver is assigned, you can use the call or chat icon on the ride tracking screen to communicate with them securely.",
    faqQuestion4: "What if I lost an item?",
    faqAnswer4: 'Go to your Ride History, select the ride where you lost the item, and tap "Report Lost Item" to get in touch with the driver.',

    // Driver registration
    driverRegistrationHeader: "Driver Registration",
    registrationStep: "STEP",
    registrationOf: "OF",
    registrationComplete: "COMPLETE",
    driverAboutTitle: "Tell us about\nyourself",
    driverUploadPhotoBtn: "Upload Profile Photo",
    driverPhotoHint: "HIGH RESOLUTION PORTRAIT\nRECOMMENDED",
    driverFullLegalNameLabel: "FULL LEGAL NAME",
    driverFullLegalNamePlaceholder: "Alex Morgan",
    driverProfessionalHeadlineLabel: "PROFESSIONAL HEADLINE",
    driverProfessionalHeadlinePlaceholder: "Experienced Chauffeur",
    driverContinueToVehicle: "Continue to Vehicle",
    driverPrivacyNote: "Your information is protected by our professional privacy standards. We only use this for background verification purposes.",
    vehicleInformationTitle: "Vehicle\n Information",
    vehicleCategoryLabel: "VEHICLE CATEGORY",
    vehicleSedan: "SEDAN",
    vehicleAuto: "AUTO",
    vehicleBike: "BIKE",
    vehicleMini: "MINI",
    vehicleSuv: "SUV",
    vehicleMakeLabel: "MAKE",
    vehicleMakePlaceholder: "Select Brand",
    vehicleModelLabel: "MODEL",
    vehicleModelPlaceholder: "Select Model",
    vehicleYearLabel: "MANUFACTURING YEAR",
    vehicleYearPlaceholder: "Select Year",
    vehicleColorLabel: "COLOR",
    vehicleColorPlaceholder: "Select Color",
    vehiclePlateNumberLabel: "PLATE NUMBER",
    vehiclePlateNumberPlaceholder: "E.O. ABC-1234",
    registrationPrevious: "Previous",
    registrationNextStep: "Next Step",
    registrationTipTitle: "Registration Tip",
    registrationTipDesc: "Ensure your vehicle details match the documents you'll upload in the next step. Accurate info helps speed up the verification process.",
    requiredDetailsTitle: "REQUIRED DETAILS",
    requiredRegistrationTitle: "Valid Registration",
    requiredRegistrationDesc: "Car must be registered in your city.",
    requiredAgeLimitTitle: "Age Limit",
    requiredAgeLimitDesc: "Vehicle must be 2010 or newer.",
    requiredInsuranceTitle: "Insurance Info",
    requiredInsuranceDesc: "Will be asked in documents step.",
    premiumCardTitle: "Elevate your driving experience\nwith Premium Category.",
    selectOptionTitle: "Select an option",
    noOptionsAvailable: "No options available",
    vehicleBrandToyota: "Toyota",
    vehicleBrandHonda: "Honda",
    vehicleBrandMercedes: "Mercedes",
    vehicleModelCorolla: "Corolla",
    vehicleModelCity: "City",
    vehicleModelEClass: "E-Class",
    vehicleYear2020: "2020",
    vehicleYear2021: "2021",
    vehicleYear2022: "2022",
    vehicleColorBlack: "Black",
    vehicleColorWhite: "White",
    vehicleColorSilver: "Silver",
    registrationStep: "STEP",
    registrationOf: "OF",

    driverUploadDocumentsTitle: "Upload\nDocuments",
    driverUploadDocumentsSubtitle: "Please provide clear photographs of your original documents for verification purposes. High-resolution scans preferred.",

    aadhaarCardTitle: "Aadhaar Card",
    aadhaarCardDesc: "Both sides of your Aadhaar card for identity verification.",
    drivingLicenseTitle: "Driving License",
    drivingLicenseDesc: "Valid commercial or LMV driving license issued in your state.",
    registrationCertificateTitle: "Registration Certificate (RC)",
    registrationCertificateDesc: "Copy of your vehicle's registration certificate.",
    insurancePolicyTitle: "Insurance Policy",
    insurancePolicyDesc: "Current active vehicle insurance policy document.",
    documentPending: "PENDING",
    documentUploaded: "UPLOADED",
    documentUpload: "Upload",
    documentChangeFile: "Change File",
    profileSelfieTitle: "Profile Selfie",
    profileSelfieDesc: "Please take a clear front-facing photo of yourself without sunglasses or hat.",
    driverTakePhoto: "Take Photo",
    driverSubmitForReview: "Submit for Review",
    driverEstimatedReviewTime: "ESTIMATED REVIEW TIME: 24–48 HOURS",
    bankPayoutTitle: "Bank Account for\nPayouts",
    bankPayoutSubtitle: "Ensure your earnings reach the right place. We use these details solely for your weekly automated payouts.",
    bankNameLabel: "BANK NAME",
    bankNamePlaceholder: "e.g. Chase National Bank",
    accountNumberLabel: "ACCOUNT NUMBER",
    accountNumberPlaceholder: "0000 0000 0000 0000",
    ifscCodeLabel: "IFSC / ROUTING CODE",
    ifscCodePlaceholder: "ABCD0123456",
    bankSecurityInfo: "Your data is encrypted using banking-grade security protocols. We do not store your full account credentials after verification.",
    verifyAndSubmit: "Verify & Submit",
    needHelpText: "Need help?",
    contactSupportText: "Contact Support",

    //Mission Screens
    missionsHeadline1: 'Push For',
    missionsHeadline2: 'The Extra.',
    missionsSubtitle: 'Track your milestones and unlock exclusive rewards. Your progress is updated in real-time.',
    missions: [
        {
            id: '1',
            tag: 'Standard Quest',
            title: 'Daily Goal',
            bonus: '₹150 Bonus',
            bonusDark: false,
            description: 'Complete 8 trips today',
            current: 5,
            target: 8,
            footer: '3 more to reach target',
            image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDD5Hmt680owIBVRWOuZLm1_Wo7RwYFtn6MpKKup6MEPQnMCCe3A_BYLua_qW1txaWaGqzvS7Lim8yp_YYyjjJ5X_gRfccheZ9x9K-_BYrwAFl9h1u6ltYedCbG7gsZf9Fm6OskvUFFxhBEsnKSYin-i13b8ynXdZBwiSLAPUCxzHI7PYLalW3I5bh7IpZ8ciIgb8z0UbG5kpvBXDuqFM4jJdoUoqUx3xWhdBgEgqhHabgLEwDxvQ0cHMeL2-nuf16NysSfhsJXo5fj',
        },
        {
            id: '2',
            tag: 'Limited Event',
            title: 'Weekend Sprint',
            bonus: '₹800 Bonus',
            bonusDark: false,
            description: 'Complete 30 trips by Sunday',
            current: 12,
            target: 30,
            footer: 'Ends in 2 days, 4 hours',
            image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDM6pgj-Pr-oDFDLJ2OQlat6T4XlgOt21dghya8Fry24hKBtIxYw5EvBJI_sWP4s2-HQvy7AMOj-U0ZvCfJrCYDeUK53MBalMMZevmPQlWPjXmW3Rlj4yApYcxIv6tgk6t96n5XUkC6PAYzuBdnVnIFOjUDlQko_OZPohRTwGk4gf8EesuPFOFKgEKhinW7UlnWM6RgasTH5YS2X-T8DNrZ1pmNippWzpRYtaB1e2db6BfzkuxHaea_xhwxxL2AXdFX6ckvhEdkS-np',
        },
        {
            id: '3',
            tag: 'Network Growth',
            title: 'Referral Mission',
            bonus: '₹500 / Ref',
            bonusDark: true,
            description: 'Invite 2 new captains',
            current: 1,
            target: 2,
            footer: 'Invite code: ZAPGLO2026',
            image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuC8vekZ7FBHOFEyw2BT0NSEHPmX7sZm2llb8EvbDpbPt-R5rYg0lulKYx9v8M9Ht0gvnY4lTopVhbJmb1BlGgEE1B6EkA3eVVxr4aUoC_MckrPcuF9DpRzdMSXIeiYQ82t4wBFbPwhTY_aOpE-OyuANDqhVNILME8sFa3-qXN1GPa7EBjgNJ5hvcTWaXr',
        },
    ],

    // Help info screen
    helpInfoHeader: 'Help & Info',
    helpInfoSubLabel: 'Partner Guide',
    helpInfoHeadline: 'Incentives & Missions',
    helpInfoSubtitle: 'Maximize your earnings through our performance-based rewards system. Designed for the silent concierge.',
    needMoreHelp: 'Need more help?',
    needMoreHelpSubtitle: 'Our concierge support team is available 24/7 for Captains.',
    contactSupportBtn: 'Contact Support',
    footerText: 'ViteRide © 2026',
    helpCards: [
        {
            id: '1',
            icon: 'stars',
            iconDark: true,
            title: 'How Missions Work',
            body: 'Missions are personalized daily or weekly goals tailored to your driving patterns. Complete a specific number of trips within the time window to unlock premium bonuses that boost your total revenue.',
            showProgress: false,
        },
        {
            id: '2',
            icon: 'query-stats',
            iconDark: false,
            title: 'Tracking Progress',
            body: 'Your performance dashboard provides real-time telemetry. The mission progress bar updates immediately after every completed trip, ensuring you always know exactly how close you are to your next reward.',
            showProgress: true,
            progressValue: 0.66,
        },
        {
            id: '3',
            icon: 'payments',
            iconDark: false,
            title: 'Reward Payouts',
            body: "Efficiency is rewarded instantly. Mission bonuses are credited to your net earnings balance the moment the goal is met. You can view these detailed breakdowns in your 'Earnings' tab under 'Bonuses'.",
            showProgress: false,
        },
    ],
};

//     // Help & Support Screen
//     helpSupportHeader: "Help & Support",
//     helpSupportHeroTitle: "How can we\nhelp?",
//     helpSupportHeroSubtitle: "Find answers to your questions or get in touch with our support team.",
//     helpSupportSearchPlaceholder: "Search for help...",
//     helpSupportSectionTitle: "BOOKING & RIDES",
//     helpSupportStillNeedHelp: "Still need help?",
//     helpSupportStillNeedHelpDesc: "Our dedicated support team is available 24/7 to assist you with any inquiries.",
//     helpSupportRaiseTicket: "Raise a Ticket",
//     faqQuestion1: "How do I change my pickup location?",
//     faqAnswer1: "You can edit your pickup location before a driver accepts your request. Simply tap the pickup address bar on the map screen and enter the new location.",
//     faqQuestion2: "What are the payment options?",
//     faqAnswer2: "We accept credit/debit cards, Apple Pay, Google Pay, and ViteRide Wallet. You can manage these in the Payment section.",
//     faqQuestion3: "How do I contact my driver?",
//     faqAnswer3: "Once a driver is assigned, you can use the call or chat icon on the ride tracking screen to communicate with them securely.",
//     faqQuestion4: "What if I lost an item?",
//     faqAnswer4: 'Go to your Ride History, select the ride where you lost the item, and tap "Report Lost Item" to get in touch with the driver.',

//     // Driver registration
//     driverRegistrationHeader: "Driver Registration",
//     registrationStep: "STEP",
//     registrationOf: "OF",
//     registrationComplete: "COMPLETE",
//     driverAboutTitle: "Tell us about\nyourself",
//     driverUploadPhotoBtn: "Upload Profile Photo",
//     driverPhotoHint: "HIGH RESOLUTION PORTRAIT\nRECOMMENDED",
//     driverFullLegalNameLabel: "FULL LEGAL NAME",
//     driverFullLegalNamePlaceholder: "Alex Morgan",
//     driverProfessionalHeadlineLabel: "PROFESSIONAL HEADLINE",
//     driverProfessionalHeadlinePlaceholder: "Experienced Chauffeur",
//     driverContinueToVehicle: "Continue to Vehicle",
//     driverPrivacyNote: "Your information is protected by our professional privacy standards. We only use this for background verification purposes.",
//     vehicleInformationTitle: "Vehicle\n Information",
//     vehicleCategoryLabel: "VEHICLE CATEGORY",
//     vehicleSedan: "SEDAN",
//     vehicleAuto: "AUTO",
//     vehicleBike: "BIKE",
//     vehicleMini: "MINI",
//     vehicleSuv: "SUV",
//     vehicleMakeLabel: "MAKE",
//     vehicleMakePlaceholder: "Select Brand",
//     vehicleModelLabel: "MODEL",
//     vehicleModelPlaceholder: "Select Model",
//     vehicleYearLabel: "MANUFACTURING YEAR",
//     vehicleYearPlaceholder: "Select Year",
//     vehicleColorLabel: "COLOR",
//     vehicleColorPlaceholder: "Select Color",
//     vehiclePlateNumberLabel: "PLATE NUMBER",
//     vehiclePlateNumberPlaceholder: "E.O. ABC-1234",
//     registrationPrevious: "Previous",
//     registrationNextStep: "Next Step",
//     registrationTipTitle: "Registration Tip",
//     registrationTipDesc: "Ensure your vehicle details match the documents you'll upload in the next step. Accurate info helps speed up the verification process.",
//     requiredDetailsTitle: "REQUIRED DETAILS",
//     requiredRegistrationTitle: "Valid Registration",
//     requiredRegistrationDesc: "Car must be registered in your city.",
//     requiredAgeLimitTitle: "Age Limit",
//     requiredAgeLimitDesc: "Vehicle must be 2010 or newer.",
//     requiredInsuranceTitle: "Insurance Info",
//     requiredInsuranceDesc: "Will be asked in documents step.",
//     premiumCardTitle: "Elevate your driving experience\nwith Premium Category.",
//     selectOptionTitle: "Select an option",
//     noOptionsAvailable: "No options available",
//     vehicleBrandToyota: "Toyota",
//     vehicleBrandHonda: "Honda",
//     vehicleBrandMercedes: "Mercedes",
//     vehicleModelCorolla: "Corolla",
//     vehicleModelCity: "City",
//     vehicleModelEClass: "E-Class",
//     vehicleYear2020: "2020",
//     vehicleYear2021: "2021",
//     vehicleYear2022: "2022",
//     vehicleColorBlack: "Black",
//     vehicleColorWhite: "White",
//     vehicleColorSilver: "Silver",
//     registrationStep: "STEP",
// registrationOf: "OF",

// driverUploadDocumentsTitle: "Upload\nDocuments",
// driverUploadDocumentsSubtitle: "Please provide clear photographs of your original documents for verification purposes. High-resolution scans preferred.",

// aadhaarCardTitle: "Aadhaar Card",
// aadhaarCardDesc: "Both sides of your Aadhaar card for identity verification.",
// drivingLicenseTitle: "Driving License",
// drivingLicenseDesc: "Valid commercial or LMV driving license issued in your state.",
// registrationCertificateTitle: "Registration Certificate (RC)",
// registrationCertificateDesc: "Copy of your vehicle's registration certificate.",
// insurancePolicyTitle: "Insurance Policy",
// insurancePolicyDesc: "Current active vehicle insurance policy document.",
// documentPending: "PENDING",
// documentUploaded: "UPLOADED",
// documentUpload: "Upload",
// documentChangeFile: "Change File",
// profileSelfieTitle: "Profile Selfie",
// profileSelfieDesc: "Please take a clear front-facing photo of yourself without sunglasses or hat.",
// driverTakePhoto: "Take Photo",
// driverSubmitForReview: "Submit for Review",
// driverEstimatedReviewTime: "ESTIMATED REVIEW TIME: 24–48 HOURS",
// bankPayoutTitle: "Bank Account for\nPayouts",
// bankPayoutSubtitle: "Ensure your earnings reach the right place. We use these details solely for your weekly automated payouts.",
// bankNameLabel: "BANK NAME",
// bankNamePlaceholder: "e.g. Chase National Bank",
// accountNumberLabel: "ACCOUNT NUMBER",
// accountNumberPlaceholder: "0000 0000 0000 0000",
// ifscCodeLabel: "IFSC / ROUTING CODE",
// ifscCodePlaceholder: "ABCD0123456",
// bankSecurityInfo: "Your data is encrypted using banking-grade security protocols. We do not store your full account credentials after verification.",
// verifyAndSubmit: "Verify & Submit",
// needHelpText: "Need help?",
// contactSupportText: "Contact Support",

